export const skillTypeGroups = [
  {
    key: 'tool',
    title: '通用工具技能',
    subtitle: '联网搜索、数学计算、时间查询、代码执行等通用原子能力',
    color: 'blue'
  },
  {
    key: 'business',
    title: '核心业务技能',
    subtitle: '图谱查询、文档检索、规则问答等项目核心业务能力',
    color: 'green'
  },
  {
    key: 'custom',
    title: '场景定制技能',
    subtitle: '访客管理、数据统计、报表生成、多轮对话梳理等组合能力',
    color: 'purple'
  }
]

export const defaultSkillModules = [
  {
    id: 'web-search',
    slug: 'web-search',
    name: '联网搜索 Skill',
    description: '用于实时资料检索、事实核验与外部来源补充。',
    skill_type: 'tool',
    category: '搜索类',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/tool/web-search',
    enabled: true,
    status: 'ready',
    load_strategy: 'lazy',
    tool_dependencies: ['web_search'],
    mcp_dependencies: [],
    skill_dependencies: [],
    scenarios: ['实时资料核验', '外部链接补充', '新闻/标准查询'],
    call_example: '查询最新计算机网络标准并给出来源。',
    params: { top_k: 5, temperature: 0.1, trace: true, timeout_ms: 15000, rate_limit_per_minute: 30 }
  },
  {
    id: 'math-calculator',
    slug: 'math-calculator',
    name: '数学计算 Skill',
    description: '用于公式计算、复杂度估算、统计指标计算和数值校验。',
    skill_type: 'tool',
    category: '计算类',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/tool/math-calculator',
    enabled: true,
    status: 'ready',
    load_strategy: 'preload',
    tool_dependencies: ['calculator'],
    mcp_dependencies: [],
    skill_dependencies: [],
    scenarios: ['复杂度计算', '指标统计', '公式校验'],
    call_example: '计算哈希查找平均时间复杂度相关指标。',
    params: { top_k: 3, temperature: 0, trace: false, timeout_ms: 5000, rate_limit_per_minute: 60 }
  },
  {
    id: 'time-query',
    slug: 'time-query',
    name: '时间查询 Skill',
    description: '用于当前时间、时区转换、日期区间和周期统计。',
    skill_type: 'tool',
    category: '时间类',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/tool/time-query',
    enabled: false,
    status: 'ready',
    load_strategy: 'lazy',
    tool_dependencies: ['time_query'],
    mcp_dependencies: [],
    skill_dependencies: [],
    scenarios: ['时间换算', '日期范围生成', '统计周期定位'],
    call_example: '把 UTC 时间换算为北京时间并生成近 7 天范围。',
    params: { top_k: 1, temperature: 0, trace: false, timeout_ms: 3000, rate_limit_per_minute: 60 }
  },
  {
    id: 'code-execution',
    slug: 'code-execution',
    name: '代码执行 Skill',
    description: '用于安全沙箱中的小段代码验证、数据处理和算法演示。',
    skill_type: 'tool',
    category: '执行类',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/tool/code-execution',
    enabled: false,
    status: 'sandboxed',
    load_strategy: 'lazy',
    tool_dependencies: ['python_repl'],
    mcp_dependencies: [],
    skill_dependencies: [],
    scenarios: ['算法验证', '数据清洗', '示例代码运行'],
    call_example: '用 Python 验证排序算法输出是否正确。',
    params: { top_k: 3, temperature: 0, trace: true, timeout_ms: 10000, rate_limit_per_minute: 10 }
  },
  {
    id: 'kg-query',
    slug: 'kg-query',
    name: '图谱查询 Skill',
    description: '用于 Neo4j/LightRAG 图谱实体查询、多跳推理与路径解释。',
    skill_type: 'business',
    category: '图谱类',
    version: '1.1.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/business/kg-query',
    enabled: true,
    status: 'ready',
    load_strategy: 'session-visible',
    tool_dependencies: ['graph_query', 'graph_reasoning'],
    mcp_dependencies: [],
    skill_dependencies: ['math-calculator'],
    scenarios: ['实体关系查询', '学习路径推荐', '多跳推理'],
    call_example: '解释 TCP 与可靠传输之间的图谱路径。',
    params: { top_k: 12, temperature: 0.2, trace: true, graph_depth: 2, retrieval_threshold: 0.72 }
  },
  {
    id: 'doc-rag-retrieval',
    slug: 'doc-rag-retrieval',
    name: '文档检索 Skill',
    description: '用于向量库 RAG 精准检索、证据重排与答案引用。',
    skill_type: 'business',
    category: '检索类',
    version: '1.1.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/business/doc-rag-retrieval',
    enabled: true,
    status: 'ready',
    load_strategy: 'session-visible',
    tool_dependencies: ['knowledge_base_search', 'rerank'],
    mcp_dependencies: [],
    skill_dependencies: ['web-search'],
    scenarios: ['教材问答', '论文检索', '证据引用'],
    call_example: '从知识库检索 OS 死锁条件并附来源。',
    params: { top_k: 8, temperature: 0.1, trace: true, retrieval_threshold: 0.68, rerank_top_n: 5 }
  },
  {
    id: 'rule-qa',
    slug: 'rule-qa',
    name: '规则问答 Skill',
    description: '用于固定规则、FAQ、评分标准和权限策略类问答。',
    skill_type: 'business',
    category: '规则类',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/business/rule-qa',
    enabled: false,
    status: 'ready',
    load_strategy: 'session-visible',
    tool_dependencies: ['rule_matcher'],
    mcp_dependencies: [],
    skill_dependencies: [],
    scenarios: ['FAQ 问答', '规则解释', '考试评分说明'],
    call_example: '按规则解释为什么该问答命中低置信度。',
    params: { top_k: 6, temperature: 0, trace: true, retrieval_threshold: 0.8 }
  },
  {
    id: 'visitor-management-query',
    slug: 'visitor-management-query',
    name: '访客管理查询 Skill',
    description: '用于访客记录、访问统计与业务状态查询。',
    skill_type: 'custom',
    category: '访客管理',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/custom/visitor-management-query',
    enabled: false,
    status: 'draft',
    load_strategy: 'triggered',
    tool_dependencies: ['query'],
    mcp_dependencies: [],
    skill_dependencies: ['rule-qa'],
    scenarios: ['访客查询', '访问趋势', '异常记录分析'],
    call_example: '查询本周访客量并按来源渠道统计。',
    params: { top_k: 10, temperature: 0.1, trace: true, max_turns: 6, output_format: 'table' }
  },
  {
    id: 'data-stat-analysis',
    slug: 'data-stat-analysis',
    name: '数据统计与分析 Skill',
    description: '用于会话统计、趋势洞察、异常数据诊断和指标解释。',
    skill_type: 'custom',
    category: '数据分析',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/custom/data-stat-analysis',
    enabled: true,
    status: 'ready',
    load_strategy: 'triggered',
    tool_dependencies: ['calculator', 'query'],
    mcp_dependencies: [],
    skill_dependencies: ['math-calculator'],
    scenarios: ['Dashboard 指标解释', '趋势分析', '异常诊断'],
    call_example: '分析最近 7 天问答活跃度下降原因。',
    params: { top_k: 10, temperature: 0, trace: true, max_turns: 8, output_format: 'markdown' }
  },
  {
    id: 'report-generation',
    slug: 'report-generation',
    name: '报表生成 Skill',
    description: '用于 SQL 查询报表、Markdown 报告和可视化图表输出。',
    skill_type: 'custom',
    category: '报表生成',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/custom/report-generation',
    enabled: false,
    status: 'ready',
    load_strategy: 'triggered',
    tool_dependencies: ['query', 'execute_modify'],
    mcp_dependencies: ['mcp-server-chart'],
    skill_dependencies: ['data-stat-analysis'],
    scenarios: ['业务报表', '图表生成', '运营周报'],
    call_example: '生成近 30 天知识库使用情况周报。',
    params: { top_k: 10, temperature: 0.2, trace: true, max_turns: 10, output_format: 'markdown' }
  },
  {
    id: 'conversation-summary',
    slug: 'conversation-summary',
    name: '多轮对话梳理 Skill',
    description: '用于多轮上下文压缩、意图追踪、待办总结与问答归档。',
    skill_type: 'custom',
    category: '对话治理',
    version: '1.0.0',
    author: 'CompKG-QA',
    dir_path: 'saves/skills/custom/conversation-summary',
    enabled: true,
    status: 'ready',
    load_strategy: 'triggered',
    tool_dependencies: [],
    mcp_dependencies: [],
    skill_dependencies: ['doc-rag-retrieval'],
    scenarios: ['多轮总结', '上下文压缩', 'QA 归档'],
    call_example: '总结本轮对话中用户最终确认的问题和结论。',
    params: { top_k: 6, temperature: 0.3, trace: false, max_turns: 12, output_format: 'markdown' }
  }
]
